language: node_js
node_js:
  - "12"
addons:
  apt:
    packages:
      - libgconf-2-4
before_install:
  - git fetch --unshallow
install:
  - yarn install
script:
  - "/bin/bash .travis/lint-commits.sh"
  - yarn test --coverage
  - yarn start & ./node_modules/.bin/wait-on http://localhost:3000
  - yarn cypress:run
after_script:
  - "/bin/bash .travis/after-script.sh"
after_success:
  - "/bin/bash .travis/after-success.sh"
git:
  depth: 1
cache:
  directories:
    - node_modules
    - "~/.cache"
notifications:
  email: false
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
